import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {NuqsAdapter} from "nuqs/adapters/next"
import { TRPCReactProvider } from "./api/trpc/client";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AutoMentor",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/bot.png", sizes: "192x192", type: "image/png" }, // for larger devices
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
      <TRPCReactProvider>
        <html lang="en">
          <body className={`${inter.className} antialiased`}>
            <Toaster />
            {children}
          </body>
        </html>
      </TRPCReactProvider>
    </NuqsAdapter>
  );
}
